package com.example.util

enum class AppLanguage(val code: String, val nativeName: String) {
  ENGLISH("en", "English"),
  HINDI("hi", "Hindi"),
  TELUGU("te", "Telugu"),
  KANNADA("kn", "Kannada"),
  TAMIL("ta", "Tamil")
}

object LocalizedStrings {
  private val strings = mapOf(
    AppLanguage.ENGLISH to mapOf(
      "app_name" to "Kisan Alert",
      "tagline" to "Quick help for weather, crop health, and mandi alerts",
      "lang_label" to "Language",
      "tab_home" to "Home",
      "tab_ask" to "Ask",
      "tab_alerts" to "Alerts",
      "tab_account" to "Account",
      "greeting_short" to "Namaste",
      "home_headline" to "Today on your farm",
      "home_intro" to "Quick help for crop health, weather, and mandi updates in one place.",
      "home_signed_in_title" to "Today for {name}",
      "home_signed_in_copy" to "Start with the next useful step for {district}. Keep advice short, local, and grounded in your {crop} crop cycle.",
      "home_weather_label" to "Weather",
      "home_weather_value" to "Rain possible tomorrow",
      "home_top_alert_label" to "Top alert",
      "home_no_alerts" to "No active alerts",
      "home_next_title" to "What should I do now?",
      "home_priority_1_title" to "Check leaves after last night rain",
      "home_priority_1_detail" to "Use the camera flow if you see fresh spots or curling.",
      "home_priority_2_title" to "Listen to the latest advisory",
      "home_priority_2_detail" to "Voice answers are useful when reading is difficult in the field.",
      "home_priority_3_title" to "Review market and weather alerts",
      "home_priority_3_detail" to "Short alerts keep the next action simple.",
      "home_support_title" to "Trusted review",
      "home_support_copy" to "If advice is unclear, replay it aloud and review it with {helper} or a local agriculture worker before spending money.",
      "home_support_button" to "Open account and support",
      "home_priority_patch_title" to "Check the wettest {crop} patch first",
      "home_priority_patch_detail" to "Moisture-linked disease spread is easier to confirm early than after a full-field spray decision.",
      "home_priority_voice_title" to "Use voice before typing long questions",
      "home_priority_voice_detail" to "Short spoken questions reduce friction, especially when the phone is shared or hands are occupied.",
      "home_priority_market_title" to "Review the {district} market signal after field checks",
      "home_priority_market_detail" to "Do the crop-saving action first, then decide whether today's mandi movement justifies transport.",
      "home_weather_anantapur" to "Light rain after 6 PM",
      "home_weather_guntur" to "Hot afternoon, calmer evening",
      "home_weather_nizamabad" to "Cloud build-up by sunset",
      "home_weather_mysuru" to "Morning showers possible",
      "home_weather_default" to "Weather check due today",
      "home_actions_title" to "Quick actions",
      "home_action_ask" to "Ask by voice or photo",
      "home_action_photo" to "Check a crop image",
      "home_action_alerts" to "See farm alerts",
      "login_eyebrow" to "Farmer-first sign in",
      "login_intro" to "Phone number first. Short steps. Voice-ready after login.",
      "login_pill_shared" to "Shared-phone friendly",
      "login_pill_simple" to "Low-text flow",
      "login_step_1" to "Step 1 of 2",
      "login_step_2" to "Step 2 of 2",
      "login_title_phone" to "Enter the mobile number used on the farm",
      "login_title_otp" to "Enter the demo OTP to continue",
      "login_copy_phone" to "This keeps sign-in familiar for rural and shared-device use. No long forms or password memory.",
      "login_copy_otp" to "For this build, use OTP 1234. Production should move to a real assisted phone-login service.",
      "login_phone_placeholder" to "10-digit mobile number",
      "login_name_placeholder" to "Farmer name",
      "login_district_placeholder" to "District",
      "login_send_otp" to "Send OTP",
      "login_otp_placeholder" to "Demo OTP 1234",
      "login_edit_number" to "Edit number",
      "login_verify_continue" to "Verify and continue",
      "login_demo_otp" to "Demo OTP: 1234",
      "ask_title" to "Ask in the easiest way",
      "ask_intro" to "Speak a question, check a crop image, or run a quick soil advisory.",
      "ask_voice_button" to "Speak your question",
      "ask_voice_listening" to "Listening...",
      "ask_photo_button" to "Try a crop image sample",
      "ask_soil_title" to "Quick soil advice",
      "ask_soil_intro" to "Use a simple preset first. Fine-grained soil entry can come later.",
      "ask_preset_rice" to "Rice",
      "ask_preset_cotton" to "Cotton",
      "ask_preset_pulses" to "Pulses",
      "ask_last_question" to "Last spoken question",
      "ask_loading_title" to "Preparing your answer...",
      "ask_loading_copy" to "This demo still calls AI directly from the device. Important recommendations should be reviewed by a human.",
      "ask_crop_answer_title" to "Crop health answer",
      "ask_soil_answer_title" to "Soil advisory",
      "ask_voice_answer_title" to "Voice guidance",
      "ask_context_hint" to "Using {crop} context for {district}. Keep the question short and ask for the next step before asking for full treatment.",
      "ask_risk_high" to "High risk",
      "ask_risk_medium" to "Medium risk",
      "ask_risk_low" to "Low risk",
      "ask_risk_plan" to "Plan before spending",
      "ask_confidence_early" to "Early guidance",
      "ask_confidence_pattern" to "Pattern-based guidance",
      "ask_confidence_prototype" to "Prototype guidance",
      "ask_confidence_soil_fit" to "Soil-fit guidance",
      "ask_review_copy" to "Review this with a trusted helper before spending on treatment.",
      "ask_summary_healthy" to "No clear disease pattern is visible right now. Keep monitoring the same patch and avoid spending on treatment before symptoms spread.",
      "ask_summary_detected" to "{risk} detected with about {percent}% visible impact in this sample. Confirm the next step on two nearby plants before treating the whole field.",
      "ask_empty_title" to "No answer yet",
      "ask_empty_copy" to "Start with voice if you are in the field. Use the image sample if you want to test crop health faster.",
      "alerts_screen_title" to "Alerts that matter now",
      "alerts_screen_intro" to "Keep alerts short, specific, and easy to share with someone nearby.",
      "alerts_context_hint" to "Alerts are ranked for {district} and your {crop} crop cycle first.",
      "alerts_read_aloud" to "Read aloud",
      "account_title" to "Farmer account",
      "account_not_signed_in" to "Not signed in",
      "account_intro" to "Simple settings for language, voice, and support.",
      "account_profile_name" to "Farmer profile",
      "account_profile_district" to "District",
      "account_profile_crop" to "Primary crop",
      "account_helper_label" to "Trusted helper",
      "account_language_voice_title" to "Language and voice",
      "account_voice_title" to "Read answers aloud",
      "account_voice_copy" to "Helpful when the phone is being shared in the field.",
      "account_language_title" to "App language",
      "account_language_copy" to "Choose the language that is easiest to understand.",
      "account_support_title" to "Support",
      "account_support_copy" to "If a recommendation is unclear, show the answer card to a local agriculture officer or trusted family member before acting.",
      "account_support_warning" to "This build is still a guided demo. Keep human review for important farm decisions.",
      "account_save_profile" to "Save profile details",
      "account_sign_out" to "Sign out",
      "voice_recognizer_prompt" to "Speak now",
      "tts_answer_intro" to "Here is the current guidance.",
      "tts_actions_intro" to "Recommended actions are:",
      "tab_advisory" to "Advisory",
      "tab_logger" to "Logger",
      "tab_history" to "RSK Logs",
      "farm_status" to "Farm Status",
      "moisture" to "Soil Moisture",
      "groundwater" to "Groundwater",
      "weather" to "Weather",
      "recent_alerts" to "Recent Safety Alerts",
      "soil_params" to "Enter Soil Parameters",
      "soil_type" to "Soil Type",
      "nitrogen" to "Nitrogen (N)",
      "phosphorus" to "Phosphorus (P)",
      "potassium" to "Potassium (K)",
      "ph_level" to "Soil pH Level",
      "run_advisory" to "Run AI Crop Advisory",
      "advisory_result" to "AI Crop Recommendation",
      "capture_leaf" to "Capture or Upload Crop Image",
      "voice_query" to "Voice Query Help",
      "diag_report" to "Diagnostic Report",
      "disease" to "Detected Issue",
      "severity" to "Severity Level",
      "remedies" to "Recommended Action Plan",
      "rsk_banner_title" to "Raitha Sahayaka Kendra (RSK) Logs",
      "rsk_banner_desc" to "Broadcasting real-time regional guidelines, market pricing, and voice warnings directly to farmers' standard mobile phones.",
      "moisture_status" to "38% (Optimal)",
      "groundwater_status" to "18m (Stable)",
      "weather_status" to "Sunny, 32°C",
      "advisory_placeholder" to "Input your soil nutrients above and tap 'Run AI Crop Advisory' to generate crop recommendations suited for your field.",
      "logger_placeholder" to "Upload an image of the plant leaf or hold the mic to describe the symptoms. Visual & spoken AI diagnostics will display here."
    ),
    AppLanguage.HINDI to mapOf(
      "app_name" to "किसान अलर्ट",
      "tagline" to "एआई और सामुदायिक सुरक्षा चेतावनी",
      "lang_label" to "भाषा",
      "tab_home" to "मुख्य",
      "tab_advisory" to "फसल सलाह",
      "tab_logger" to "स्वास्थ्य लॉगर",
      "tab_history" to "आरएसके लॉग्स",
      "farm_status" to "खेत की स्थिति",
      "moisture" to "मिट्टी की नमी",
      "groundwater" to "भूजल स्तर",
      "weather" to "मौसम",
      "recent_alerts" to "हालिया सुरक्षा चेतावनी",
      "soil_params" to "मिट्टी के मापदंड दर्ज करें",
      "soil_type" to "मिट्टी का प्रकार",
      "nitrogen" to "नाइट्रोजन (N)",
      "phosphorus" to "फास्फोरस (P)",
      "potassium" to "पोटेशियम (K)",
      "ph_level" to "मिट्टी का पीएच (pH)",
      "run_advisory" to "एआई फसल सलाह चलाएं",
      "advisory_result" to "एआई फसल अनुशंसा",
      "capture_leaf" to "पत्ती की फोटो खींचें या अपलोड करें",
      "voice_query" to "आवाज द्वारा प्रश्न पूछें",
      "diag_report" to "जांच रिपोर्ट",
      "disease" to "पहचानी गई बीमारी",
      "severity" to "गंभीरता का स्तर",
      "remedies" to "अनुशंसित उपचार योजना",
      "rsk_banner_title" to "रायतु भरोसा केंद्र / आरएसके लॉग्स",
      "rsk_banner_desc" to "किसानों के साधारण मोबाइल फोन पर वास्तविक समय में क्षेत्रीय सलाह, बाजार भाव और वॉयस कॉल चेतावनी भेजना।",
      "moisture_status" to "38% (सामान्य)",
      "groundwater_status" to "18 मीटर (স্থिर)",
      "weather_status" to "धूप, 32°C",
      "advisory_placeholder" to "ऊपर मिट्टी के पोषक तत्व भरें और अपने खेत के अनुकूल फसल सुझाव प्राप्त करने के लिए 'एआई फसल सलाह चलाएं' पर टैप करें।",
      "logger_placeholder" to "पौधे की पत्ती की तस्वीर अपलोड करें या लक्षणों को बताने के लिए माइक बटन दबाएं। विज़ुअल और वॉयस रिपोर्ट यहाँ दिखाई देगी।"
    ),
    AppLanguage.TELUGU to mapOf(
      "app_name" to "కిసాన్ అలర్ట్",
      "tagline" to "AI & కమ్యూనిటీ హెచ్చరికలు",
      "lang_label" to "భాష",
      "tab_home" to "హోమ్",
      "tab_advisory" to "పంట సలహా",
      "tab_logger" to "ఆరోగ్య లాగర్",
      "tab_history" to "RSK లాగ్స్",
      "farm_status" to "పంట క్షేత్ర స్థితి",
      "moisture" to "నేల తేమ",
      "groundwater" to "భూగర్భ జల మట్టం",
      "weather" to "వాతావరణం",
      "recent_alerts" to "ఇటీవలి హెచ్చరికలు",
      "soil_params" to "నేల కొలతలను నమోదు చేయండి",
      "soil_type" to "నేల రకం",
      "nitrogen" to "నత్రజని (N)",
      "phosphorus" to "భాస్వరం (P)",
      "potassium" to "పొటాషియం (K)",
      "ph_level" to "నేల pH విలువ",
      "run_advisory" to "AI పంట సలహా రన్ చేయి",
      "advisory_result" to "AI పంట సిఫార్సు",
      "capture_leaf" to "ఆకు ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి",
      "voice_query" to "వాయిస్ ప్రశ్న సలహా",
      "diag_report" to "పంట వ్యాధి నిర్ధారణ నివేదిక",
      "disease" to "గుర్తించిన సమస్య",
      "severity" to "తీవ్రత స్థాయి",
      "remedies" to "సూచించిన నివారణ చర్యలు",
      "rsk_banner_title" to "రైతు సేవా కేంద్రం (RSK) లాగ్స్",
      "rsk_banner_desc" to "రైతుల సాధారణ మొబైల్ ఫోన్‌లకు నేరుగా రియల్ టైమ్ వాయిస్ కాల్స్ మరియు ఎస్ఎంఎస్ ద్వారా సమాచారం చేరవేయడం.",
      "moisture_status" to "38% (అనుకూలం)",
      "groundwater_status" to "18 మీటర్లు (స్థిరంగా)",
      "weather_status" to "ఎండగా ఉంది, 32°C",
      "advisory_placeholder" to "పైన మీ నేల పోషకాలను నమోదు చేసి, మీ పొలానికి సరిపోయే పంట సిఫార్సులను పొందడానికి 'AI పంట సలహా రన్ చేయి' పై నొక్కండి.",
      "logger_placeholder" to "మొక్క ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి లేదా మైక్ నొక్కి సమస్యను వివరించండి. వ్యాధి నిర్ధారణ ఇక్కడ చూపబడుతుంది."
    ),
    AppLanguage.KANNADA to mapOf(
      "app_name" to "ಕಿಸಾನ್ ಅಲರ್ಟ್",
      "tagline" to "AI ಮತ್ತು ಸಮುದಾಯ ಎಚ್ಚರಿಕೆ ವ್ಯವಸ್ಥೆ",
      "lang_label" to "ಭಾಷೆ",
      "tab_home" to "ಮುಖಪುಟ",
      "tab_advisory" to "ಬೆಳೆ ಸಲಹೆ",
      "tab_logger" to "ಆರೋಗ್ಯ ಲಾಗರ್",
      "tab_history" to "RSK ಇತಿಹಾಸ",
      "farm_status" to "ಫಾರ್ಮ್ ಸ್ಥಿತಿ",
      "moisture" to "ಮಣ್ಣಿನ ತೇವಾಂಶ",
      "groundwater" to "ಅಂತರ್ಜಲ ಮಟ್ಟ",
      "weather" to "ಹವಾಮಾನ",
      "recent_alerts" to "ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು",
      "soil_params" to "ಮಣ್ಣಿನ ನಿಯತಾಂಕಗಳನ್ನು ನಮೂದಿಸಿ",
      "soil_type" to "ಮಣ್ಣಿನ ಪ್ರಕಾರ",
      "nitrogen" to "ಸಾರಜನಕ (N)",
      "phosphorus" to "ರಂಜಕ (P)",
      "potassium" to "ಪೊಟ್ಯಾಸಿಯಮ್ (K)",
      "ph_level" to "ಮಣ್ಣಿನ pH ಮಟ್ಟ",
      "run_advisory" to "AI ಬೆಳೆ ಸಲಹೆ ರನ್ ಮಾಡಿ",
      "advisory_result" to "AI ಬೆಳೆ ಶಿಫಾರಸು",
      "capture_leaf" to "ಎಲೆಯ ಚಿತ್ರವನ್ನು ತೆಗೆಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
      "voice_query" to "ಧ್ವನಿ ಮೂಲಕ ಪ್ರಶ್ನಿಸಿ",
      "diag_report" to "ರೋಗ ಪತ್ತೆ ವರದಿ",
      "disease" to "ಪತ್ತೆಯಾದ ರೋಗ",
      "severity" to "ರೋಗದ ತೀವ್ರತೆ",
      "remedies" to "ಶಿಫಾರಸು ಮಾಡಿದ ಪರಿಹಾರಗಳು",
      "rsk_banner_title" to "ರೈತ ಸಂಪರ್ಕ ಕೇಂದ್ರ (RSK) ಇತಿಹಾಸ",
      "rsk_banner_desc" to "ರೈತರ ಸಾಮಾನ್ಯ ಮೊಬೈಲ್ ಫೋನ್‌ಗಳಿಗೆ ನೇರವಾಗಿ ಧ್ವನಿ ಕರೆ ಮತ್ತು SMS ಮೂಲಕ ತುರ್ತು ಕೃಷಿ ಮಾಹಿತಿಯನ್ನು ಕಳುಹಿಸುವುದು.",
      "moisture_status" to "38% (ಸೂಕ್ತ)",
      "groundwater_status" to "18 ಮೀ (ಸ್ಥಿರ)",
      "weather_status" to "ಬಿಸಿಲು, 32°C",
      "advisory_placeholder" to "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಮಣ್ಣಿನ ಪೌಷ್ಟಿಕಾಂಶಗಳನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಮಣ್ಣಿಗೆ ಹೊಂದುವ ಬೆಳೆ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಲು 'AI ಬೆಳೆ ಸಲಹೆ ರನ್ ಮಾಡಿ' ಟ್ಯಾಪ್ ಮಾಡಿ.",
      "logger_placeholder" to "ಸಸ್ಯದ ಎಲೆಯ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಲು ಮೈಕ್ ಒತ್ತಿರಿ. ರೋಗ ಪತ್ತೆ ಮಾಹಿತಿಯು ಇಲ್ಲಿ ಮೂಡಿಬರುತ್ತದೆ."
    ),
    AppLanguage.TAMIL to mapOf(
      "app_name" to "கிசான் அலர்ட்",
      "tagline" to "AI மற்றும் சமூக எச்சரிக்கை சேவை",
      "lang_label" to "மொழி",
      "tab_home" to "முகப்பு",
      "tab_advisory" to "பயிர் ஆலோசனை",
      "tab_logger" to "சுகாதார லாகர்",
      "tab_history" to "RSK பதிவுகள்",
      "farm_status" to "பண்ணை நிலை",
      "moisture" to "மண் ஈரப்பதம்",
      "groundwater" to "நிலத்தடி நீர்",
      "weather" to "வானிலை",
      "recent_alerts" to "சமீபத்திய எச்சரிக்கைகள்",
      "soil_params" to "மண் அளவீடுகளை உள்ளிடவும்",
      "soil_type" to "மண் வகை",
      "nitrogen" to "நைட்ரஜன் (N)",
      "phosphorus" to "பாஸ்பரஸ் (P)",
      "potassium" to "பொட்டாசியம் (K)",
      "ph_level" to "மண் pH அளவு",
      "run_advisory" to "AI பயிர் ஆலோசனையை இயக்கு",
      "advisory_result" to "AI பயிர் பரிந்துரை",
      "capture_leaf" to "இலையைப் படம் பிடிக்கவும் அல்லது பதிவேற்றவும்",
      "voice_query" to "குரல் வழி கேள்வி கேட்க",
      "diag_report" to "நோய் கண்டறிதல் அறிக்கை",
      "disease" to "கண்டறியப்பட்ட நோய்",
      "severity" to "தீவிரத்தன்மை",
      "remedies" to "பரிந்துரைக்கப்பட்ட தீர்வுகள்",
      "rsk_banner_title" to "உழவர் உதவி மையம் (RSK) பதிவுகள்",
      "rsk_banner_desc" to "விவசாயிகளின் சாதாரண மொபைல் போன்களுக்கு நேரடியாக குரல் அழைப்புகள் மற்றும் SMS மூலமாக எச்சரிக்கைகளை அனுப்புதல்.",
      "moisture_status" to "38% (சிறந்தது)",
      "groundwater_status" to "18மீ (நிலையானது)",
      "weather_status" to "வெயில், 32°C",
      "advisory_placeholder" to "மண் அளவீடுகளை மேலே உள்ளிட்டு, உங்களது நிலத்திற்கு ஏற்ற சிறந்த பயிர்களைப் பற்றி அறிய 'AI பயிர் ஆலோசனையை இயக்கு' என்பதைத் தட்டவும்.",
      "logger_placeholder" to "பயிரின் இலை புகைப்படத்தை பதிவேற்றவும் அல்லது அறிகுறிகளை விளக்க மைக் பொத்தானை அழுத்தவும். நோய் கண்டறிதல் அறிக்கை இங்கே காட்டப்படும்."
    )
  )

  fun get(key: String, lang: AppLanguage): String {
    return strings[lang]?.get(key) ?: strings[AppLanguage.ENGLISH]?.get(key) ?: key
  }

  fun format(key: String, lang: AppLanguage, replacements: Map<String, String>): String {
    var value = get(key, lang)
    replacements.forEach { (token, content) ->
      value = value.replace("{$token}", content)
    }
    return value
  }
}
