package com.example.util

enum class AppLanguage(val code: String, val nativeName: String) {
  ENGLISH("en", "English"),
  HINDI("hi", "हिंदी (Hindi)"),
  TELUGU("te", "తెలుగు (Telugu)"),
  KANNADA("kn", "ಕನ್ನಡ (Kannada)"),
  TAMIL("ta", "தமிழ் (Tamil)")
}

object LocalizedStrings {
  private val strings = mapOf(
    AppLanguage.ENGLISH to mapOf(
      "app_name" to "Kisan Alert",
      "tagline" to "AI & Community Warning Broadcasts",
      "lang_label" to "Language",
      "tab_home" to "Home",
      "tab_advisory" to "Advisory",
      "tab_logger" to "Logger",
      "tab_history" to "RSK Logs",
      "farm_status" to "Farm Status",
      "moisture" to "Soil Moisture",
      "groundwater" to "Groundwater",
      "weather" to "Weather",
      "recent_alerts" to "Recent Safety Alerts",
      "soil_params" to "Enter Soil Parameters",
      "soil_type" to "Soil Type",
      "nitrogen" to "Nitrogen (N)",
      "phosphorus" to "Phosphorus (P)",
      "potassium" to "Potassium (K)",
      "ph_level" to "Soil pH Level",
      "run_advisory" to "Run AI Crop Advisory",
      "advisory_result" to "AI Crop Recommendation",
      "capture_leaf" to "Capture or Upload Crop Image",
      "voice_query" to "Voice Query Help",
      "diag_report" to "Diagnostic Report",
      "disease" to "Detected Issue",
      "severity" to "Severity Level",
      "remedies" to "Recommended Action Plan",
      "rsk_banner_title" to "Raitha Sahayaka Kendra (RSK) Logs",
      "rsk_banner_desc" to "Broadcasting real-time regional guidelines, market pricing, and voice warnings directly to farmers' standard mobile phones.",
      "moisture_status" to "38% (Optimal)",
      "groundwater_status" to "18m (Stable)",
      "weather_status" to "Sunny, 32°C",
      "advisory_placeholder" to "Input your soil nutrients above and tap 'Run AI Crop Advisory' to generate crop recommendations suited for your field.",
      "logger_placeholder" to "Upload an image of the plant leaf or hold the mic to describe the symptoms. Visual & spoken AI diagnostics will display here."
    ),
    AppLanguage.HINDI to mapOf(
      "app_name" to "किसान अलर्ट",
      "tagline" to "एआई और सामुदायिक सुरक्षा चेतावनी",
      "lang_label" to "भाषा",
      "tab_home" to "मुख्य",
      "tab_advisory" to "फसल सलाह",
      "tab_logger" to "स्वास्थ्य लॉगर",
      "tab_history" to "आरएसके लॉग्स",
      "farm_status" to "खेत की स्थिति",
      "moisture" to "मिट्टी की नमी",
      "groundwater" to "भूजल स्तर",
      "weather" to "मौसम",
      "recent_alerts" to "हालिया सुरक्षा चेतावनी",
      "soil_params" to "मिट्टी के मापदंड दर्ज करें",
      "soil_type" to "मिट्टी का प्रकार",
      "nitrogen" to "नाइट्रोजन (N)",
      "phosphorus" to "फास्फोरस (P)",
      "potassium" to "पोटेशियम (K)",
      "ph_level" to "मिट्टी का पीएच (pH)",
      "run_advisory" to "एआई फसल सलाह चलाएं",
      "advisory_result" to "एआई फसल अनुशंसा",
      "capture_leaf" to "पत्ती की फोटो खींचें या अपलोड करें",
      "voice_query" to "आवाज द्वारा प्रश्न पूछें",
      "diag_report" to "जांच रिपोर्ट",
      "disease" to "पहचानी गई बीमारी",
      "severity" to "गंभीरता का स्तर",
      "remedies" to "अनुशंसित उपचार योजना",
      "rsk_banner_title" to "रायतु भरोसा केंद्र / आरएसके लॉग्स",
      "rsk_banner_desc" to "किसानों के साधारण मोबाइल फोन पर वास्तविक समय में क्षेत्रीय सलाह, बाजार भाव और वॉयस कॉल चेतावनी भेजना।",
      "moisture_status" to "38% (सामान्य)",
      "groundwater_status" to "18 मीटर (স্থिर)",
      "weather_status" to "धूप, 32°C",
      "advisory_placeholder" to "ऊपर मिट्टी के पोषक तत्व भरें और अपने खेत के अनुकूल फसल सुझाव प्राप्त करने के लिए 'एआई फसल सलाह चलाएं' पर टैप करें।",
      "logger_placeholder" to "पौधे की पत्ती की तस्वीर अपलोड करें या लक्षणों को बताने के लिए माइक बटन दबाएं। विज़ुअल और वॉयस रिपोर्ट यहाँ दिखाई देगी।"
    ),
    AppLanguage.TELUGU to mapOf(
      "app_name" to "కిసాన్ అలర్ట్",
      "tagline" to "AI & కమ్యూనిటీ హెచ్చరికలు",
      "lang_label" to "భాష",
      "tab_home" to "హోమ్",
      "tab_advisory" to "పంట సలహా",
      "tab_logger" to "ఆరోగ్య లాగర్",
      "tab_history" to "RSK లాగ్స్",
      "farm_status" to "పంట క్షేత్ర స్థితి",
      "moisture" to "నేల తేమ",
      "groundwater" to "భూగర్భ జల మట్టం",
      "weather" to "వాతావరణం",
      "recent_alerts" to "ఇటీవలి హెచ్చరికలు",
      "soil_params" to "నేల కొలతలను నమోదు చేయండి",
      "soil_type" to "నేల రకం",
      "nitrogen" to "నత్రజని (N)",
      "phosphorus" to "భాస్వరం (P)",
      "potassium" to "పొటాషియం (K)",
      "ph_level" to "నేల pH విలువ",
      "run_advisory" to "AI పంట సలహా రన్ చేయి",
      "advisory_result" to "AI పంట సిఫార్సు",
      "capture_leaf" to "ఆకు ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి",
      "voice_query" to "వాయిస్ ప్రశ్న సలహా",
      "diag_report" to "పంట వ్యాధి నిర్ధారణ నివేదిక",
      "disease" to "గుర్తించిన సమస్య",
      "severity" to "తీవ్రత స్థాయి",
      "remedies" to "సూచించిన నివారణ చర్యలు",
      "rsk_banner_title" to "రైతు సేవా కేంద్రం (RSK) లాగ్స్",
      "rsk_banner_desc" to "రైతుల సాధారణ మొబైల్ ఫోన్‌లకు నేరుగా రియల్ టైమ్ వాయిస్ కాల్స్ మరియు ఎస్ఎంఎస్ ద్వారా సమాచారం చేరవేయడం.",
      "moisture_status" to "38% (అనుకూలం)",
      "groundwater_status" to "18 మీటర్లు (స్థిరంగా)",
      "weather_status" to "ఎండగా ఉంది, 32°C",
      "advisory_placeholder" to "పైన మీ నేల పోషకాలను నమోదు చేసి, మీ పొలానికి సరిపోయే పంట సిఫార్సులను పొందడానికి 'AI పంట సలహా రన్ చేయి' పై నొక్కండి.",
      "logger_placeholder" to "మొక్క ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి లేదా మైక్ నొక్కి సమస్యను వివరించండి. వ్యాధి నిర్ధారణ ఇక్కడ చూపబడుతుంది."
    ),
    AppLanguage.KANNADA to mapOf(
      "app_name" to "ಕಿಸಾನ್ ಅಲರ್ಟ್",
      "tagline" to "AI ಮತ್ತು ಸಮುದಾಯ ಎಚ್ಚರಿಕೆ ವ್ಯವಸ್ಥೆ",
      "lang_label" to "ಭಾಷೆ",
      "tab_home" to "ಮುಖಪುಟ",
      "tab_advisory" to "ಬೆಳೆ ಸಲಹೆ",
      "tab_logger" to "ಆರೋಗ್ಯ ಲಾಗರ್",
      "tab_history" to "RSK ಇತಿಹಾಸ",
      "farm_status" to "ಫಾರ್ಮ್ ಸ್ಥಿತಿ",
      "moisture" to "ಮಣ್ಣಿನ ತೇವಾಂಶ",
      "groundwater" to "ಅಂತರ್ಜಲ ಮಟ್ಟ",
      "weather" to "ಹವಾಮಾನ",
      "recent_alerts" to "ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು",
      "soil_params" to "ಮಣ್ಣಿನ ನಿಯತಾಂಕಗಳನ್ನು ನಮೂದಿಸಿ",
      "soil_type" to "ಮಣ್ಣಿನ ಪ್ರಕಾರ",
      "nitrogen" to "ಸಾರಜನಕ (N)",
      "phosphorus" to "ರಂಜಕ (P)",
      "potassium" to "ಪೊಟ್ಯಾಸಿಯಮ್ (K)",
      "ph_level" to "ಮಣ್ಣಿನ pH ಮಟ್ಟ",
      "run_advisory" to "AI ಬೆಳೆ ಸಲಹೆ ರನ್ ಮಾಡಿ",
      "advisory_result" to "AI ಬೆಳೆ ಶಿಫಾರಸು",
      "capture_leaf" to "ಎಲೆಯ ಚಿತ್ರವನ್ನು ತೆಗೆಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
      "voice_query" to "ಧ್ವನಿ ಮೂಲಕ ಪ್ರಶ್ನಿಸಿ",
      "diag_report" to "ರೋಗ ಪತ್ತೆ ವರದಿ",
      "disease" to "ಪತ್ತೆಯಾದ ರೋಗ",
      "severity" to "ರೋಗದ ತೀವ್ರತೆ",
      "remedies" to "ಶಿಫಾರಸು ಮಾಡಿದ ಪರಿಹಾರಗಳು",
      "rsk_banner_title" to "ರೈತ ಸಂಪರ್ಕ ಕೇಂದ್ರ (RSK) ಇತಿಹಾಸ",
      "rsk_banner_desc" to "ರೈತರ ಸಾಮಾನ್ಯ ಮೊಬೈಲ್ ಫೋನ್‌ಗಳಿಗೆ ನೇರವಾಗಿ ಧ್ವನಿ ಕರೆ ಮತ್ತು SMS ಮೂಲಕ ತುರ್ತು ಕೃಷಿ ಮಾಹಿತಿಯನ್ನು ಕಳುಹಿಸುವುದು.",
      "moisture_status" to "38% (ಸೂಕ್ತ)",
      "groundwater_status" to "18 ಮೀ (ಸ್ಥಿರ)",
      "weather_status" to "ಬಿಸಿಲು, 32°C",
      "advisory_placeholder" to "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಮಣ್ಣಿನ ಪೌಷ್ಟಿಕಾಂಶಗಳನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಮಣ್ಣಿಗೆ ಹೊಂದುವ ಬೆಳೆ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಲು 'AI ಬೆಳೆ ಸಲಹೆ ರನ್ ಮಾಡಿ' ಟ್ಯಾಪ್ ಮಾಡಿ.",
      "logger_placeholder" to "ಸಸ್ಯದ ಎಲೆಯ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಲು ಮೈಕ್ ಒತ್ತಿರಿ. ರೋಗ ಪತ್ತೆ ಮಾಹಿತಿಯು ಇಲ್ಲಿ ಮೂಡಿಬರುತ್ತದೆ."
    ),
    AppLanguage.TAMIL to mapOf(
      "app_name" to "கிசான் அலர்ட்",
      "tagline" to "AI மற்றும் சமூக எச்சரிக்கை சேவை",
      "lang_label" to "மொழி",
      "tab_home" to "முகப்பு",
      "tab_advisory" to "பயிர் ஆலோசனை",
      "tab_logger" to "சுகாதார லாகர்",
      "tab_history" to "RSK பதிவுகள்",
      "farm_status" to "பண்ணை நிலை",
      "moisture" to "மண் ஈரப்பதம்",
      "groundwater" to "நிலத்தடி நீர்",
      "weather" to "வானிலை",
      "recent_alerts" to "சமீபத்திய எச்சரிக்கைகள்",
      "soil_params" to "மண் அளவீடுகளை உள்ளிடவும்",
      "soil_type" to "மண் வகை",
      "nitrogen" to "நைட்ரஜன் (N)",
      "phosphorus" to "பாஸ்பரஸ் (P)",
      "potassium" to "பொட்டாசியம் (K)",
      "ph_level" to "மண் pH அளவு",
      "run_advisory" to "AI பயிர் ஆலோசனையை இயக்கு",
      "advisory_result" to "AI பயிர் பரிந்துரை",
      "capture_leaf" to "இலையைப் படம் பிடிக்கவும் அல்லது பதிவேற்றவும்",
      "voice_query" to "குரல் வழி கேள்வி கேட்க",
      "diag_report" to "நோய் கண்டறிதல் அறிக்கை",
      "disease" to "கண்டறியப்பட்ட நோய்",
      "severity" to "தீவிரத்தன்மை",
      "remedies" to "பரிந்துரைக்கப்பட்ட தீர்வுகள்",
      "rsk_banner_title" to "உழவர் உதவி மையம் (RSK) பதிவுகள்",
      "rsk_banner_desc" to "விவசாயிகளின் சாதாரண மொபைல் போன்களுக்கு நேரடியாக குரல் அழைப்புகள் மற்றும் SMS மூலமாக எச்சரிக்கைகளை அனுப்புதல்.",
      "moisture_status" to "38% (சிறந்தது)",
      "groundwater_status" to "18மீ (நிலையானது)",
      "weather_status" to "வெயில், 32°C",
      "advisory_placeholder" to "மண் அளவீடுகளை மேலே உள்ளிட்டு, உங்களது நிலத்திற்கு ஏற்ற சிறந்த பயிர்களைப் பற்றி அறிய 'AI பயிர் ஆலோசனையை இயக்கு' என்பதைத் தட்டவும்.",
      "logger_placeholder" to "பயிரின் இலை புகைப்படத்தை பதிவேற்றவும் அல்லது அறிகுறிகளை விளக்க மைக் பொத்தானை அழுத்தவும். நோய் கண்டறிதல் அறிக்கை இங்கே காட்டப்படும்."
    )
  )

  fun get(key: String, lang: AppLanguage): String {
    return strings[lang]?.get(key) ?: strings[AppLanguage.ENGLISH]?.get(key) ?: key
  }
}
